### ISSUE TITLE
Joi Validation Schemas are not been used

### ISSUE THREAD

**Issue by mickeymond** [aaron-portuphy/taskhub-backend#1]
@aaron-portuphy You are validation schemas defined in your code that are not been used leading to Internal Server Error in all cases.
```
{
    "error": "Internal server error"
}
```

**Comment by aaron-portuphy** [comment]
> @aaron-portuphy You are validation schemas defined in your code that are not been used leading to Internal Server Error in all cases.
> 
> ```
> {
>     "error": "Internal server error"
> }
> ```

All the joi validation schemas are actually been used in the sign up, however only two are being used in the login, I had the internal server error but later resolved it and my end points were working. Perhaps we can look at it together during our call today.

**Comment by aaron-portuphy** [comment]
Hello Michael, I have been able to resolve the internal server error now. Thank you.
